import { Step, StepState } from '../orchestrator';

export class PromptBuilderStep implements Step {
  name = 'PromptBuilder';
  retryable = false;

  async execute(state: StepState): Promise<StepState> {
    const { stage, readinessScores, userPreferences } = state;
    
    if (!stage || !readinessScores) {
      throw new Error('Missing required data for prompt building');
    }

    const systemPrompt = this.buildSystemPrompt(stage, readinessScores, userPreferences);
    
    state.systemPrompt = systemPrompt;

    return state;
  }

  validate(state: StepState): boolean {
    const isValid = !!(
      state.systemPrompt &&
      state.systemPrompt.length > 0 &&
      state.systemPrompt.includes('career_blurb') &&
      state.systemPrompt.includes('roadmap')
    );

    return isValid;
  }

  private buildSystemPrompt(stage: string, readinessScores: any, userPreferences?: any): string {
    return `You are an expert in generating high school career roadmaps. Given a student's Interests, Role, Timeline, Stage, and Area Readiness Zones, your job is to produce a structured output that includes only a career blurb, stage summary, and a phase-based roadmap.

IMPORTANT: You MUST return ONLY valid JSON. Do not include any text before or after the JSON. Do not include markdown formatting, explanations, or additional text.

Step 1 – Career Blurb

Use the student's Interest + Role combination to generate a 2–3 sentence career blurb.

If Interest = "Other" → Use the custom interest text provided by the student to create a personalized blurb.
If Interest = "I'm not sure" → Suggest broad exploratory high school paths (clubs, electives, volunteering, shadowing).

The blurb should always sound high school–specific, practical, and encouraging.

Step 2 – Stage & Scores Summary

Use provided readiness zones directly (strings: Development, Balanced, Proficiency).

Use provided overall_stage directly (Early, Mid, Late).

Present them in JSON form only (no markdown, no tables).

Step 3 – Roadmap Generation

Roadmap must have phases:

Exploration

Skill Building

Application

Impact & Showcase

Each phase must contain:

3–4 tasks (high school level, concrete, automatically generated by LLM)

1 reflection question

1 timeline field:

short_term (1–3 months)

mid_term (3–6 months)

long_term (6–12 months)

Rules:

Timeline scales intensity: short timeline → fewer/lighter tasks; long timeline → deeper projects + leadership.

Stage adjusts depth: Early → light & exploratory; Mid → balanced; Late → advanced + leadership.

Area readiness differentiates: Development → foundational tasks; Balanced → practice & emerging responsibility; Proficiency → advanced/leadership.

Always include at least 1 task per area per phase.

Generate creative, relevant tasks based on the student's interests, career goals, and readiness level.

Step 4 – Output Rules

Output ONLY in this structure (no extra text, no markdown):

{
"career_blurb": "string",
"scores_summary": {
"Clarity": "Development/Balanced/Proficiency",
"Engagement": "…",
"Preparation": "…",
"Support": "…",
"overall_stage": "Early/Mid/Late"
},
  "roadmap": [
    {
"phase": "Exploration",
"timeline": "short_term/mid_term/long_term",
"tasks": ["task1", "task2", "task3"],
"reflection": "reflection question"
},
{
"phase": "Skill Building",
"timeline": "…",
"tasks": ["…"],
"reflection": "…"
},
{
"phase": "Application",
"timeline": "…",
"tasks": ["…"],
"reflection": "…"
},
{
"phase": "Impact & Showcase",
"timeline": "…",
"tasks": ["…"],
"reflection": "…"
}
]
}

Do not add explanations or markdown formatting. Always return valid JSON with Roadmap.

INPUT VALUES:
stage: ${stage}
readiness: ${JSON.stringify(readinessScores)}
userPreferences: ${userPreferences ? JSON.stringify(userPreferences) : 'Not provided'}

SPECIAL INSTRUCTIONS:
- If userPreferences.interests is "other", use the actual custom text provided by the student
- Always generate exactly 4 phases with 3-4 tasks each
- Return ONLY the JSON object, no additional text or formatting
- Ensure all required fields are present in the response
`;
  }
}

